const dogs = [
  { id: 'oakley', name: 'Oakley', meta: 'Yellow · Female · English Labrador Retriever', description: 'Our current breeding female with a natural hunting drive and a family-companion focus.', image: "url('https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=1100&q=85')", link: '#oakley-profile' },
  { id: 'kobee', name: 'Kobee', meta: 'Black · Male · English Labrador Retriever', description: 'One of the current Labradors in our growing program. More information will be shared as available.', image: "url('https://images.unsplash.com/photo-1537151608828-ea2b11777ee8?auto=format&fit=crop&w=1100&q=85')", link: '#kobee-profile' }
];
const cards = document.querySelector('#dog-cards');
cards.innerHTML = dogs.map(d => `<article class="dog-card"><div class="dog-card-image" style="background-image:${d.image}" role="img" aria-label="${d.name} the ${d.meta}"><span class="photo-note">Placeholder photo</span></div><div class="dog-card-content"><h3>${d.name}</h3><p class="dog-meta">${d.meta}</p><p>${d.description}</p><a class="text-link" href="${d.link}">View ${d.name}'s profile <span aria-hidden="true">→</span></a></div></article>`).join('');
const kobee = document.createElement('section');
kobee.className = 'section detail-page'; kobee.id = 'kobee-profile';
kobee.innerHTML = `<div class="detail-header"><p class="eyebrow">Dog profile</p><h2>Kobee</h2><p>Black English Labrador Retriever · Male</p></div><div class="detail-grid"><article><h3>About Kobee</h3><p class="placeholder">[Information to be added]</p></article><article><h3>Health & genetic testing</h3><p class="placeholder">[Information to be added]</p></article><article><h3>Temperament, activities & accomplishments</h3><p class="placeholder">[Information to be added]</p></article><article><h3>Registration & pedigree</h3><p class="placeholder">[Information to be added]</p></article></div><p class="small-note">Kobee gallery: Westwind photographs to be added.</p>`;
document.querySelector('#oakley-profile').after(kobee);
document.querySelector('#year').textContent = new Date().getFullYear();
const menuButton = document.querySelector('.menu-button'), nav = document.querySelector('nav');
menuButton.addEventListener('click', () => { const open = nav.classList.toggle('open'); menuButton.setAttribute('aria-expanded', open); });
nav.addEventListener('click', e => { if(e.target.matches('a')) { nav.classList.remove('open'); menuButton.setAttribute('aria-expanded','false'); } });
const form = document.querySelector('#puppy-application'), status = document.querySelector('.form-status');
form.addEventListener('submit', async e => { e.preventDefault(); status.className='form-status'; const invalid = [...form.querySelectorAll('[required]')].filter(field => !field.value.trim()); if(invalid.length){ status.textContent = `Please complete the required field${invalid.length > 1 ? 's' : ''}: ${invalid.map(f => f.closest('label')?.childNodes[0]?.textContent?.trim()).filter(Boolean).join(', ')}.`; status.classList.add('error'); invalid[0].focus(); status.focus(); return; } const data = Object.fromEntries(new FormData(form)); if(data.website) return; const submit = form.querySelector('[type=submit]'); submit.disabled=true; submit.textContent='Submitting…'; try { const response=await fetch('/.netlify/functions/application',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}); if(!response.ok) throw new Error(); status.textContent='Thank you — your application has been submitted. We’ll be in touch after reviewing it.'; status.classList.add('success'); form.reset(); status.focus(); } catch { status.textContent='We could not submit your application right now. Please email contact@westwindlabradors.com for assistance.'; status.classList.add('error'); status.focus(); } finally { submit.disabled=false; submit.textContent='Submit Puppy Application'; }});
