const dogs = [
  { name:'Oakley', meta:'Yellow · Female · English Labrador Retriever', description:'Our current breeding female with a natural hunting drive and a family-companion focus.', image:"url('assets/oakley-cover.png')", link:'oakley.html' }
];
const cards = document.querySelector('#dog-cards');
if (cards) cards.innerHTML = dogs.map(d => `<article class="dog-card dog-card--framed"><div class="dog-card-image dog-card-image--full-art" style="background-image:${d.image}" role="img" aria-label="${d.name} the ${d.meta}"></div><div class="dog-card-content"><h3>${d.name}</h3><p class="dog-meta">${d.meta}</p><p>${d.description}</p><a class="text-link" href="${d.link}">View ${d.name}'s Profile <span aria-hidden="true">→</span></a></div></article>`).join('');
document.querySelectorAll('.menu-button').forEach(button => { const nav = document.querySelector('#site-nav'); button.addEventListener('click', () => { const open = nav.classList.toggle('open'); button.setAttribute('aria-expanded', open); }); });
document.querySelectorAll('[data-year]').forEach(el => el.textContent = new Date().getFullYear());
document.querySelectorAll('.brand').forEach(brand => { brand.classList.add('brand-art'); brand.innerHTML = `<img src="assets/westwind-logo-crop.png" alt="Westwind Labradors" />`; });
const hero = document.querySelector('.hero');
if (hero) { hero.querySelector('h1')?.classList.add('sr-only'); hero.querySelector('.hero-copy')?.classList.add('sr-only'); hero.querySelector('.eyebrow')?.classList.add('sr-only'); hero.querySelector('.photo-note')?.remove(); const art = hero.querySelector('[role="img"]'); if (art) art.setAttribute('aria-label','Westwind Labradors illustrated cover artwork featuring a yellow Labrador, pine trees, mountains, and a lake at sunset'); }
if (hero) document.querySelector('.intro')?.remove();
if (hero) { document.querySelector('.dogs')?.remove(); document.querySelector('.approach')?.remove(); }
if (hero) document.querySelector('.litter-content')?.remove();
if (location.pathname.endsWith('/dogs.html')) { const dogsHero = document.querySelector('.page-hero'); dogsHero?.querySelector('.eyebrow')?.remove(); dogsHero?.querySelector('p:last-child')?.remove(); dogsHero?.querySelector('h1')?.replaceChildren('The Heart of Westwind'); }
if (location.pathname.endsWith('/dogs.html')) document.querySelector('.registration')?.remove();
if (location.pathname.endsWith('/litter.html')) { const litterPageHero = document.querySelector('.page-hero'); litterPageHero?.querySelector('.eyebrow')?.remove(); litterPageHero?.querySelector('p:last-child')?.remove(); const litterTitle = litterPageHero?.querySelector('h1'); if (litterTitle && !litterPageHero.querySelector('.litter-due-date')) litterTitle.insertAdjacentHTML('afterend','<p class="litter-due-date">Due Oct. 18, 2026</p>'); }
if (location.pathname.endsWith('/litter.html')) document.querySelector('.litter-details')?.remove();
const sireStyle = document.createElement('style');
sireStyle.textContent = '.sire-information{background:#f3e6cd}.sire-information-heading{max-width:780px;margin:0 auto 2rem;text-align:center}.sire-information-heading h2{margin-bottom:1.5rem}.sire-facts{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin:0}.sire-facts div{padding:1rem;border-top:1px solid #cdbb98}.sire-facts dt{font-size:.72rem;font-weight:700;letter-spacing:.12em;text-transform:uppercase}.sire-facts dd{margin:.25rem 0 0;font-family:Fraunces,serif;font-size:1.25rem}.sire-graphics{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1.5rem;max-width:1100px;margin:auto}.sire-graphics figure{margin:0;border:clamp(5px,1vw,12px) solid #f7e7c6;box-shadow:0 0 0 2px #8d5936,0 8px 20px rgba(45,33,18,.18);background:#261e16}.sire-graphics img{display:block;width:100%;height:auto}.sire-graphics .sire-cover{grid-row:span 2;align-self:start}@media(max-width:700px){.sire-facts,.sire-graphics{grid-template-columns:1fr}.sire-graphics .sire-cover{grid-row:auto}}';
document.head.append(sireStyle);
const announcementImage = 'assets/upcoming-litter-announcement.png';
const homeLitterImage = document.querySelector('.litter-image');
if (homeLitterImage) { homeLitterImage.classList.add('litter-image--announcement'); homeLitterImage.style.backgroundImage = `url('${announcementImage}')`; homeLitterImage.setAttribute('aria-label','Westwind Labradors upcoming litter announcement featuring Oakley and Kobee, the sire'); }
if (location.pathname.endsWith('/litter.html')) { const litterHero = document.querySelector('.page-hero'); if (litterHero) { const announcement = document.createElement('figure'); announcement.style.cssText = 'margin:0;background:#211e16;padding:clamp(1rem,4vw,3rem) clamp(1rem,8vw,8rem);'; announcement.innerHTML = `<img src="${announcementImage}" alt="Westwind Labradors upcoming litter announcement featuring Oakley and Kobee, the sire" style="display:block;width:100%;height:auto;max-width:1680px;margin:auto;">`; litterHero.after(announcement); } }
if (location.pathname.endsWith('/litter.html') && !document.querySelector('.sire-information')) { const announcement = document.querySelector('.page-hero + figure'); announcement?.insertAdjacentHTML('afterend','<section class="sire-information section" aria-labelledby="sire-information-title"><div class="sire-information-heading"><h2 id="sire-information-title">Sire Information</h2><dl class="sire-facts"><div><dt>Name</dt><dd>Kobee</dd></div><div><dt>Breeder</dt><dd>Hedge Lane Labradors</dd></div><div><dt>Color</dt><dd>Black</dd></div></dl></div><div class="sire-graphics"><figure class="sire-cover"><img src="assets/kobee-cover.jpeg" alt="Kobee, a black Labrador Retriever, in a supplied profile graphic"></figure><figure><img src="assets/kobee-ofa-elbows.jpeg" alt="Supplied OFA elbow dysplasia evaluation report for Kobee"></figure><figure><img src="assets/kobee-pedigree.jpeg" alt="Supplied certified pedigree for Kobee"></figure></div></section>'); }
if (location.pathname.endsWith('/puppies.html')) { const puppiesHero = document.querySelector('.page-hero'); puppiesHero?.querySelector('.eyebrow')?.remove(); const puppyArt = document.querySelector('.puppy-art'); if (puppyArt) { puppyArt.style.backgroundImage = "url('assets/puppies-oakley-cover.png')"; puppyArt.setAttribute('aria-label','Oakley, a yellow English Labrador Retriever, in Westwind Labradors cover artwork'); puppyArt.classList.add('puppy-art--oakley'); } }
const puppiesArtStyle = document.createElement('style');
puppiesArtStyle.textContent = '.puppy-art--oakley{width:100%;max-width:100%;height:auto;aspect-ratio:1/1;min-height:0;background-size:contain;background-repeat:no-repeat;background-position:center;background-color:#261e16;border:clamp(5px,1vw,12px) solid #f7e7c6;box-shadow:0 0 0 2px #8d5936,0 12px 30px rgba(45,33,18,.22)}';
document.head.append(puppiesArtStyle);
const oakleyProfileImage = document.querySelector('.profile-photo');
if (oakleyProfileImage) { oakleyProfileImage.style.backgroundImage = "url('assets/oakley-cover.png')"; oakleyProfileImage.setAttribute('aria-label','Oakley, a yellow English Labrador Retriever, in Westwind Labradors cover artwork'); }
if (location.pathname.endsWith('/oakley.html')) { const profileCopy = document.querySelector('.profile-copy'); profileCopy?.querySelector('h2')?.remove(); const bio = profileCopy?.querySelector('p:not(.eyebrow)'); if (bio) bio.outerHTML = `<div class="oakley-bio"><p>Oakley is so much more than just a beautiful yellow Labrador. She is truly one of those special dogs who has a way of becoming part of your heart.</p><p>From the very beginning, Oakley was the most playful puppy in the bunch! She has always been incredibly intelligent, eager to learn, and full of personality. She absolutely loves a good game of fetch and could happily play catch with you all day long.</p><p>Oakley also has a wonderful natural drive for hunting. She is focused, athletic, and loves having a job to do, while still being incredibly gentle and affectionate at home.</p><p>One of our favorite things about Oakley is the way she is with children. She is patient, gentle, and naturally nurturing, making her such a wonderful family dog. And that sweet nature is especially evident with our own boys.</p><p>Oakley has formed a particularly special bond with our little boy who has Type 1 diabetes. When his blood sugar is low and he isn’t feeling well, Oakley will often quietly come sit beside him and snuggle close. She seems to know when he needs a little extra comfort, and watching their bond is something truly special.</p><p>Oakley is the perfect combination of intelligence, playfulness, drive, gentleness, and loyalty—and we are so proud to have her as part of the Westwind Labradors family.</p><p>She truly is a special girl, inside and out. She is going to make the best momma to her puppies!</p></div>`; oakleyProfileImage?.classList.add('profile-photo--framed'); document.querySelector('.detail-grid h3')?.replaceChildren('Health Testing'); const healthResults = document.querySelectorAll('.check-list li span'); if (healthResults[0]) healthResults[0].textContent = 'Good'; if (healthResults[1]) healthResults[1].textContent = 'Normal'; const pedigreeHeading = [...document.querySelectorAll('.detail-grid h3')].find(h => h.textContent.trim() === 'Pedigree'); const pedigreeArticle = pedigreeHeading?.closest('article'); if (pedigreeArticle) { pedigreeArticle.classList.add('pedigree-document'); pedigreeArticle.querySelector('p')?.remove(); pedigreeArticle.insertAdjacentHTML('beforeend','<img class="pedigree-image" src="assets/oakley-pedigree-landscape.jpg" alt="Oakley’s certified pedigree, displayed in landscape orientation">'); } }
document.querySelector('.dogs .section-heading h2')?.replaceChildren('The Heart of Westwind');
const oakleyCardStyle = document.createElement('style');
oakleyCardStyle.textContent = '.dog-card--framed{border:clamp(5px,1vw,12px) solid #f7e7c6;box-shadow:0 0 0 2px #8d5936,0 12px 30px rgba(45,33,18,.22)}.dog-card-image--full-art{height:auto;aspect-ratio:1/1;background-size:contain;background-repeat:no-repeat;background-color:#261e16}';
document.head.append(oakleyCardStyle);
const litterAnnouncementStyle = document.createElement('style');
litterAnnouncementStyle.textContent = '.litter-feature{grid-template-columns:1fr;padding:clamp(1rem,3vw,2.5rem);gap:clamp(1rem,3vw,2.5rem);background:#dbc9a9}.litter-image--announcement{width:min(100%,1500px);min-height:0;aspect-ratio:1670/940;margin:auto;background-size:contain;background-repeat:no-repeat;background-color:#251f16;border:clamp(5px,1vw,12px) solid #f7e7c6;box-shadow:0 0 0 2px #8d5936,0 12px 30px rgba(45,33,18,.22)}.litter-content{padding:clamp(2rem,6vw,6rem)}@media(max-width:800px){.litter-feature{padding:1rem}.litter-image--announcement{width:100%}}';
document.head.append(litterAnnouncementStyle);
const oakleyProfileStyle = document.createElement('style');
oakleyProfileStyle.textContent = '.profile-photo--framed{border:clamp(5px,1vw,12px) solid #f7e7c6;box-shadow:0 0 0 2px #8d5936,0 12px 30px rgba(45,33,18,.22)}.oakley-bio p{margin-bottom:1.25rem}.pedigree-document{grid-column:1/-1}.pedigree-image{display:block;width:100%;height:auto;border:3px solid #cdbb98;margin-top:1rem}';
document.head.append(oakleyProfileStyle);
if (location.pathname.endsWith('/oakley.html')) { const healthItems = document.querySelectorAll('.check-list li'); healthItems[2]?.remove(); const activitiesHeading = [...document.querySelectorAll('.detail-grid h3')].find(h => h.textContent.trim() === 'Temperament & activities'); activitiesHeading?.closest('article')?.remove(); const pedigreeSection = [...document.querySelectorAll('.detail-grid h3')].find(h => h.textContent.trim() === 'Pedigree')?.closest('article'); if (pedigreeSection && !document.querySelector('.registration-document')) pedigreeSection.insertAdjacentHTML('afterend','<article class="registration-document"><h3>AKC Registration</h3><img class="registration-image" src="assets/oakley-registration-certificate.png" alt="Oakley’s American Kennel Club registration certificate"></article>'); }
const documentSizingStyle = document.createElement('style');
documentSizingStyle.textContent = '.pedigree-image,.registration-image{display:block;width:50%;height:auto;margin:1rem auto 0;border:3px solid #cdbb98}.registration-document{grid-column:1/-1}.registration-document h3{margin-bottom:0}@media(max-width:800px){.pedigree-image,.registration-image{width:100%}}';
document.head.append(documentSizingStyle);
if (location.pathname.endsWith('/oakley.html')) { const galleryHeading = [...document.querySelectorAll('.detail-grid h3')].find(h => h.textContent.trim() === 'Gallery'); const gallerySection = galleryHeading?.closest('article'); const galleryPhotos = [{file:'oakley-gallery-01.jpeg',alt:'Oakley as a young yellow Labrador walking beside a child outdoors'},{file:'oakley-gallery-02.jpeg',alt:'Oakley as a yellow Labrador puppy resting in green grass'},{file:'oakley-gallery-03.jpeg',alt:'Oakley resting indoors as a young yellow Labrador'},{file:'oakley-gallery-04.jpeg',alt:'Oakley sitting outdoors on a green lawn'},{file:'oakley-gallery-05.jpeg',alt:'Oakley resting indoors beside a child'},{file:'oakley-gallery-06.jpeg',alt:'Oakley as a puppy relaxing on a porch beside a child'},{file:'oakley-gallery-07.jpeg',alt:'Oakley standing outdoors at sunset'}]; if (gallerySection) { gallerySection.classList.add('oakley-gallery-section'); gallerySection.querySelector('p')?.remove(); gallerySection.insertAdjacentHTML('beforeend',`<div class="oakley-gallery">${galleryPhotos.map(photo=>`<figure><img src="assets/${photo.file}" alt="${photo.alt}" loading="lazy"></figure>`).join('')}</div>`); } }
const galleryStyle = document.createElement('style');
galleryStyle.textContent = '.oakley-gallery-section{grid-column:1/-1}.oakley-gallery{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1.25rem;margin-top:1rem}.oakley-gallery figure{margin:0;border:clamp(5px,1vw,12px) solid #f7e7c6;box-shadow:0 0 0 2px #8d5936,0 8px 20px rgba(45,33,18,.18);background:#261e16}.oakley-gallery img{display:block;width:100%;aspect-ratio:4/3;object-fit:cover}.oakley-gallery figure:nth-child(3) img{object-position:center top}.oakley-gallery figure:nth-child(7) img{object-position:center bottom}@media(max-width:650px){.oakley-gallery{grid-template-columns:1fr}.oakley-gallery img{aspect-ratio:auto}}';
document.head.append(galleryStyle);
const mobileHomeHeroStyle = document.createElement('style');
mobileHomeHeroStyle.textContent = '@media(max-width:800px){.hero{min-height:0;aspect-ratio:2048/762;display:block;background:#241f17}.hero-image{background-size:contain;background-repeat:no-repeat;background-position:center}.hero-content{position:absolute;inset:0;width:auto;margin:0;padding:0 .75rem .75rem;display:flex;align-items:flex-end;justify-content:center}.hero-content .actions{width:max-content;max-width:100%;padding:.45rem .65rem;gap:.75rem}}';
document.head.append(mobileHomeHeroStyle);
